#!/usr/bin/with-contenv bash

# used https://github.com/linuxserver/docker-wikijs/blob/master/root/etc/s6-overlay/s6-rc.d/svc-wikijs/run as a template

echo -e "\nApp is starting!"
#apt-get update -y && apt-get install -y firefox
apt-get purge python3 -y
apt-get autoremove -y
exec \
	  s6-setuidgid abc /entry.sh
