# .github/workflows/build-wheels.yml
name: Build Python Wheels

on:
  workflow_dispatch: # Permet un déclenchement manuel
  push:
    branches:
      - main 
      - Holaf_tests 
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-wheels.yml'

jobs:
  compile_wheels:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Le checkout se fait dans /github/workspace (par défaut dans le conteneur)

      - name: Install build dependencies (Python, pip, compilers)
        run: |
          apt-get update
          apt-get install -y -q=2 --no-install-recommends \
            software-properties-common \
            python3.11 python3.11-distutils python3.11-venv python3-pip python3.11-dev \
            wget git cmake build-essential gcc-12 g++-12 ninja-build
          update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
          update-alternatives --set python3 /usr/bin/python3.11
          update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1
          update-alternatives --set python /usr/bin/python3.11
          python3 -m pip install --upgrade pip
          pip3 install torch==2.6.0 torchvision packaging cython==0.29.37

      - name: Set Build Environment Variables
        run: |
          echo "CC=/usr/bin/gcc-12" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-12" >> $GITHUB_ENV
          echo "TORCH_CUDA_ARCH_LIST=8.6 8.9 9.0" >> $GITHUB_ENV # Ajuste si besoin
          echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/local/cuda/include${CPLUS_INCLUDE_PATH:+:${CPLUS_INCLUDE_PATH}}" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/usr/local/cuda/lib64${LIBRARY_PATH:+:${LIBRARY_PATH}}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV
          echo "NVIDIA_DRIVER_CAPABILITIES=compute,utility" >> $GITHUB_ENV
          echo "NVIDIA_VISIBLE_DEVICES=all" >> $GITHUB_ENV

      # Le répertoire de travail courant est /github/workspace (ou équivalent dans le conteneur)
      - name: Create temporary wheels directory
        run: mkdir -p wheels_output # Crée /github/workspace/wheels_output

      - name: Build flash-attention wheel
        run: |
          git clone https://github.com/Dao-AILab/flash-attention --recurse-submodules
          cd flash-attention
          python3 setup.py bdist_wheel
          cp dist/*.whl ../wheels_output/ # Copie vers /github/workspace/wheels_output
          cd .. # Retour à /github/workspace
          rm -rf flash-attention

      - name: Check for cuda_runtime.h before diso build
        run: |
          echo "--- Checking CUDA_HOME: $CUDA_HOME"
          echo "--- Checking CPLUS_INCLUDE_PATH: $CPLUS_INCLUDE_PATH"
          echo "--- Checking LIBRARY_PATH: $LIBRARY_PATH"
          echo "--- Checking LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          if [ -f /usr/local/cuda/include/cuda_runtime.h ]; then
            echo "cuda_runtime.h found at /usr/local/cuda/include/cuda_runtime.h"
          else
            echo "cuda_runtime.h NOT found at /usr/local/cuda/include/cuda_runtime.h"
            echo "Contents of /usr/local/cuda/include/:"
            ls -la /usr/local/cuda/include/
            exit 1 
          fi
          echo "--- Checking nvcc version ---"
          nvcc --version || echo "nvcc not found"

      - name: Build diso wheel
        run: |
          git clone https://github.com/SarahWeiii/diso --recurse-submodules
          cd diso
          python3 setup.py bdist_wheel
          cp dist/*.whl ../wheels_output/
          cd ..
          rm -rf diso
          
      - name: Build nvdiffrast wheel
        run: |
          git clone https://github.com/NVlabs/nvdiffrast.git
          cd nvdiffrast
          python3 setup.py bdist_wheel
          cp dist/*.whl ../wheels_output/
          cd ..
          rm -rf nvdiffrast

      - name: Build kaolin wheel
        run: |
          git clone https://github.com/NVIDIAGameWorks/kaolin.git
          cd kaolin
          python3 setup.py bdist_wheel
          cp dist/*.whl ../wheels_output/
          cd ..
          rm -rf kaolin

      - name: Build mip-splatting (diff-gaussian-rasterization) wheel
        run: |
          git clone https://github.com/autonomousvision/mip-splatting --recurse-submodules
          cd mip-splatting/submodules/diff-gaussian-rasterization
          python3 setup.py bdist_wheel
          cp dist/*.whl ../../../wheels_output/ # Copie vers /github/workspace/wheels_output
          cd ../../../ # Retour à /github/workspace
          rm -rf mip-splatting

      - name: Build TRELLIS (vox2seq) wheel
        run: |
          git clone https://github.com/microsoft/TRELLIS --recurse-submodules
          cd TRELLIS/extensions/vox2seq
          python3 setup.py bdist_wheel
          cp dist/*.whl ../../../wheels_output/ # Copie vers /github/workspace/wheels_output
          cd ../../../ # Retour à /github/workspace
          rm -rf TRELLIS
      
      - name: Commit wheels to repository
        run: |
          echo "Current directory before git commands: $(pwd)"
          echo "Content of current directory (checking for .git):"
          ls -A # DEVRAIT être la racine du checkout et contenir .git
          
          if [ ! -d ".git" ]; then
            echo "ERROR: .git directory not found in $(pwd). This is not a git repository."
            # Pour déboguer davantage si cela échoue encore :
            echo "GITHUB_WORKSPACE is: ${{ github.workspace }}"
            echo "Listing GITHUB_WORKSPACE content:"
            ls -A ${{ github.workspace }} # Devrait être identique à `ls -A` si pwd est correct
            exit 1
          fi
          
          # Le répertoire de destination des wheels dans le dépôt
          # Ce chemin est relatif au CWD, qui doit être la racine du dépôt.
          mkdir -p precompiled_wheels 
          
          # Copier les wheels compilées de ./wheels_output/ vers ./precompiled_wheels/
          cp wheels_output/*.whl precompiled_wheels/
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add precompiled_wheels/*.whl
          
          if ! git diff --staged --quiet; then
            git commit -m "Build: Update precompiled Python wheels"
            # S'assurer que la branche sur laquelle on push est correcte si besoin
            # git push origin HEAD:${{ github.ref_name }} # Par exemple, pour pusher sur la branche actuelle
            git push
          else
            echo "No new wheels to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}