name: Build and Push Buildbase Image

on:
  workflow_dispatch: # Déclenchement manuel
  push:
    branches:
      - '**' # Ou ta branche de développement principale
    paths:
      - 'Dockerfile.buildbase'
      - '.github/workflows/build-buildbase-image.yml' # Si ce workflow lui-même change

jobs:
  build_and_push_buildbase:
    name: Build and Push stable-diffusion-buildbase
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

          # all of these default to true, but feel free to set to
          # false if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for buildbase image
        id: meta-buildbase
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/stable-diffusion-buildbase
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push compilation environment image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.buildbase
          push: true
          tags: ${{ steps.meta-buildbase.outputs.tags }}
          labels: ${{ steps.meta-buildbase.outputs.labels }}
          platforms: linux/amd64
          no-cache: true
          cache-from: type=gha
          cache-to: type=gha,mode=max