# .github/workflows/publishImage.yml
name: Publish Docker images

on:
  push:
    tags: 
      - '*.*.*'
    paths: 
      - 'Dockerfile'
      - 'Dockerfile.buildenv' 
      - 'docker/**'
      - '*.sh' 
      - 'parameters/**'
      - 'custom-sample.sh'
      - 'functions.sh'
      - '.github/workflows/publishImage.yml' 
      - 'precompiled_wheels/**' 
    paths-ignore:
      - '**.md'
  workflow_dispatch: 
  workflow_run: 
    workflows: ["Build Python Wheels"] 
    types:
      - completed

jobs:
  build_compile_environment:
    name: Build and Push Compilation Environment Image
    runs-on: ubuntu-latest
    permissions:
      packages: write 
      contents: read   
    outputs: 
      image_tag: ${{ steps.meta-buildenv.outputs.tags }}
      image_name: ghcr.io/${{ github.repository_owner }}/stable-diffusion-buildenv 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for buildenv image
        id: meta-buildenv
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/stable-diffusion-buildenv
          tags: | 
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push compilation environment image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.buildenv 
          push: true 
          tags: ${{ steps.meta-buildenv.outputs.tags }}
          labels: ${{ steps.meta-buildenv.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push_final_image_to_registry: 
    name: Build and Push Final Docker image
    runs-on: ubuntu-latest
    needs: build_compile_environment 
    if: | 
      (vars.DOCKERHUB_IMAGE_NAME != '' || vars.GHCR_IMAGE_NAME != '') &&
      (github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'))
    permissions:
      packages: write 
      contents: read   
    steps:
      - name: Free Disk Space (optional)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true       # Correction ici
          android: true          # Chaque paramètre sur une nouvelle ligne
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Check out the repo
        uses: actions/checkout@v4 

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request' && vars.DOCKERHUB_IMAGE_NAME != '' && secrets.DOCKER_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && vars.GHCR_IMAGE_NAME != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for final Docker image
        id: meta-final
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.DOCKERHUB_IMAGE_NAME }}
            ${{ vars.GHCR_IMAGE_NAME }}
          tags: | 
            type=raw,value=latest,enable={{is_default_branch || github.ref_type == 'tag'}} 
            type=ref,event=branch 
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx 
        uses: docker/setup-buildx-action@v3

      - name: Build and push final Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile 
          push: ${{ github.event_name != 'pull_request' && !env.ACT}}
          tags: ${{ steps.meta-final.outputs.tags }}
          labels: ${{ steps.meta-final.outputs.labels }}
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max